name: deploy to staging

on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code ğŸ‘ŒğŸ‘ŒğŸ‘ŒğŸ‘ŒğŸ‘ŒğŸ‘Œ
        uses: actions/checkout@v2

      - name: Deploy Heroku ğŸš€ğŸš€ğŸš€ğŸš€ğŸš€ğŸš€
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_PROD_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          appdir: "eShop-DHA"
          usedocker: true